version: '3.8'
services:
  birthday-reminder-postgres:
    container_name: birthday-reminder-postgres
    image: postgres:14.2-alpine
    ports:
      - 8000:5432
    volumes:
      - /app/birthday-reminder/db:/var/lib/postgresql/data
    env_file:
      - .production.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  birthday-reminder-migration:
    container_name: birthday-reminder-migration
    image: antgoncharik/birthday-reminder-server
    env_file:
      - .production.env
    command: sh -c "/app/node_modules/.bin/db-migrate up"
    depends_on:
      birthday-reminder-postgres:
        condition: service_healthy
  birthday-reminder-server:
    container_name: birthday-reminder-server
    image: antgoncharik/birthday-reminder-server
    ports:
      - '8001:3000'
    env_file:
      - .production.env
    depends_on:
      birthday-reminder-postgres:
        condition: service_healthy
      birthday-reminder-migration:
        condition: service_completed_successfully
