version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.2-alpine
    ports:
      - 8000:5432
    volumes:
      - /app/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  migration:
    container_name: migration
    image: antgoncharik/birthday-reminder-server
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    command: sh -c "/app/node_modules/.bin/db-migrate up"
    depends_on:
      db:
        condition: service_healthy
  server:
    container_name: server
    image: antgoncharik/birthday-reminder-server
    ports:
      - '8001:3000'
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
