name: birthday-reminder-production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DB_DRIVER: ${{ secrets.DB_DRIVER }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
      - uses: actions/checkout@v3

      # - name: Build image
      #   run: docker-compose -f docker-compose.production.yml build

      # - name: Show image
      #   run: docker image ls

      # - name: Push image to Docker Hub
      #   run:

  # deploy:
  # runs-on: ubuntu-latest
  # needs:
  # - build
  # steps:
  # - uses:
  # - name:
  # run:
