name: production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DB_DRIVER: ${{secrets.DB_DRIVER}}
  DB_USER: ${{secrets.DB_USER}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_HOST: ${{secrets.DB_HOST}}
  DB_NAME: ${{secrets.DB_NAME}}
  DB_PORT: ${{secrets.DB_PORT}}
  NODE_ENV: ${{secrets.NODE_ENV}}
  SSH: ssh -T ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}
  WORKDIR: birthday-reminder-backend

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build image1
        run: ls

      - name: Build image
        run: docker build -t ${{secrets.DOCKERHUB_ACCOUNT}}/${{secrets.DOCKERHUB_IMAGE_NAME}} ~/Dockerfile.production

      - name: Login to DockerHub
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{secrets.DOCKERHUB_ACCOUNT}}/${{secrets.DOCKERHUB_IMAGE_NAME}}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
      - name: SSH setting
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          echo "${{secrets.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa

      - name: ENV setting
        run: |
          ${{env.SSH}} rm -f .profile
          ${{env.SSH}} touch .profile
          ${{env.SSH}} echo 'export DB_DRIVER=${{secrets.DB_DRIVER}} >> .profile'
          ${{env.SSH}} echo 'export DB_USER=${{secrets.DB_USER}} >> .profile'
          ${{env.SSH}} echo 'export DB_PASSWORD=${{secrets.DB_PASSWORD}} >> .profile'
          ${{env.SSH}} echo 'export DB_HOST=${{secrets.DB_HOST}} >> .profile'
          ${{env.SSH}} echo 'export DB_NAME=${{secrets.DB_NAME}} >> .profile'
          ${{env.SSH}} echo 'export DB_PORT=${{secrets.DB_PORT}} >> .profile'
          ${{env.SSH}} echo 'export NODE_ENV=${{secrets.NODE_ENV}} >> .profile'

      - name: Stop containers
        run: ${{env.SSH}} docker-compose -f ${{env.WORKDIR}}/docker-compose.production.yml down

      - name: Run containers
        run: ${{env.SSH}} docker-compose -f ${{env.WORKDIR}}/docker-compose.production.yml up -d
