name: production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DB_DRIVER: ${{ secrets.DB_DRIVER }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker-compose -f docker-compose.production.yml build

      - name: Rename image
        run: docker tag birthday-reminder-server antgoncharik/birthday-reminder-server

      # - name: Login to DockerHub
      #   run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Token
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} > ./token

      - name: Login to DockerHub
        run: cat ./token | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # - uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push antgoncharik/birthday-reminder-server

  # deploy:
  # runs-on: ubuntu-latest
  # needs:
  # - build
  # steps:
  # - uses:
  # - name:
  # run:
