name: production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DB_DRIVER: ${{ secrets.DB_DRIVER }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  NODE_ENV: ${{ secrets.NODE_ENV }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker-compose -f docker-compose.production.yml build

      - name: Rename image
        run: docker tag birthday-reminder-server antgoncharik/birthday-reminder-server

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
#
# - uses: docker/login-action@v1
#   env:
#     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#   with:
#     username: $DOCKERHUB_USERNAME
#     password: $DOCKERHUB_TOKEN
#     logout: true

# - name: Login to DockerHub
#   env:
#     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#   run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

# - name: Push image to Docker Hub
#   run: docker push antgoncharik/birthday-reminder-server

# deploy:
# runs-on: ubuntu-latest
# needs:
# - build
# steps:
# - uses:
# - name:
# run:
