name: CI-CD-pipeline-to-VPS

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world! 
        
      - name: Build container image
        run: 

      - name: Push image to Docker Hub
        run: 
        
  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - uses: 
      - name: 
        run: 

