name: production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DB_DRIVER: ${{ secrets.DB_DRIVER }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker-compose -f docker-compose.production.yml build

      - name: Login to Docker Hub
        run: docker login --username=${{env.DOCKER_USERNAME}} --email=${{env.DOCKER_EMAIL}}

      - name: Rename image
        run: docker tag birthday-reminder-server antgoncharik/birthday-reminder-server

      - name: Push image to Docker Hub
        run: docker push antgoncharik/birthday-reminder-server

  # deploy:
  # runs-on: ubuntu-latest
  # needs:
  # - build
  # steps:
  # - uses:
  # - name:
  # run:
